// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P05Shop.API.Models;

#nullable disable

namespace P05Shop.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260911085301_AddInitialData")]
    partial class AddInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("P06Shop.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Barcode = "8",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 585.877247451282m,
                            ReleaseDate = new DateTime(2026, 8, 15, 6, 7, 3, 148, DateTimeKind.Local).AddTicks(7563),
                            Title = "Fantastic Fresh Gloves"
                        },
                        new
                        {
                            Id = 2,
                            Barcode = "8",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 529.589840147919m,
                            ReleaseDate = new DateTime(2026, 6, 15, 2, 17, 48, 657, DateTimeKind.Local).AddTicks(9454),
                            Title = "Ergonomic Wooden Cheese"
                        },
                        new
                        {
                            Id = 3,
                            Barcode = "0",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 439.181953936434m,
                            ReleaseDate = new DateTime(2025, 10, 22, 16, 57, 39, 68, DateTimeKind.Local).AddTicks(3733),
                            Title = "Intelligent Plastic Chicken"
                        },
                        new
                        {
                            Id = 4,
                            Barcode = "8",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 476.239197481535m,
                            ReleaseDate = new DateTime(2026, 6, 17, 17, 0, 42, 908, DateTimeKind.Local).AddTicks(4315),
                            Title = "Gorgeous Soft Pants"
                        },
                        new
                        {
                            Id = 5,
                            Barcode = "1",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 647.728195340712m,
                            ReleaseDate = new DateTime(2025, 12, 21, 8, 22, 14, 15, DateTimeKind.Local).AddTicks(415),
                            Title = "Fantastic Granite Ball"
                        },
                        new
                        {
                            Id = 6,
                            Barcode = "7",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 477.091525651557m,
                            ReleaseDate = new DateTime(2025, 9, 17, 15, 28, 51, 440, DateTimeKind.Local).AddTicks(908),
                            Title = "Unbranded Steel Car"
                        },
                        new
                        {
                            Id = 7,
                            Barcode = "4",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 615.480758703072m,
                            ReleaseDate = new DateTime(2026, 3, 28, 23, 58, 40, 337, DateTimeKind.Local).AddTicks(6053),
                            Title = "Generic Steel Pants"
                        },
                        new
                        {
                            Id = 8,
                            Barcode = "6",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 28.6544425253079m,
                            ReleaseDate = new DateTime(2026, 2, 5, 7, 42, 56, 4, DateTimeKind.Local).AddTicks(6410),
                            Title = "Intelligent Fresh Salad"
                        },
                        new
                        {
                            Id = 9,
                            Barcode = "6",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 349.030380745898m,
                            ReleaseDate = new DateTime(2026, 1, 30, 19, 22, 24, 786, DateTimeKind.Local).AddTicks(1612),
                            Title = "Fantastic Wooden Table"
                        },
                        new
                        {
                            Id = 10,
                            Barcode = "7",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 848.389565332043m,
                            ReleaseDate = new DateTime(2026, 3, 31, 1, 26, 52, 218, DateTimeKind.Local).AddTicks(8520),
                            Title = "Ergonomic Metal Bike"
                        },
                        new
                        {
                            Id = 11,
                            Barcode = "5",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 986.58874038448m,
                            ReleaseDate = new DateTime(2026, 4, 22, 3, 16, 44, 981, DateTimeKind.Local).AddTicks(7766),
                            Title = "Small Plastic Shirt"
                        },
                        new
                        {
                            Id = 12,
                            Barcode = "6",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 366.218003555302m,
                            ReleaseDate = new DateTime(2026, 9, 2, 0, 19, 1, 828, DateTimeKind.Local).AddTicks(3523),
                            Title = "Incredible Steel Chicken"
                        },
                        new
                        {
                            Id = 13,
                            Barcode = "0",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 424.228819234403m,
                            ReleaseDate = new DateTime(2025, 11, 24, 4, 42, 48, 955, DateTimeKind.Local).AddTicks(9184),
                            Title = "Intelligent Soft Car"
                        },
                        new
                        {
                            Id = 14,
                            Barcode = "4",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 570.416535940681m,
                            ReleaseDate = new DateTime(2026, 6, 30, 15, 37, 1, 47, DateTimeKind.Local).AddTicks(7672),
                            Title = "Handmade Wooden Tuna"
                        },
                        new
                        {
                            Id = 15,
                            Barcode = "0",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 387.912313662894m,
                            ReleaseDate = new DateTime(2026, 6, 27, 13, 25, 38, 405, DateTimeKind.Local).AddTicks(1929),
                            Title = "Incredible Granite Chair"
                        },
                        new
                        {
                            Id = 16,
                            Barcode = "2",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 960.830080752648m,
                            ReleaseDate = new DateTime(2025, 10, 24, 11, 20, 11, 500, DateTimeKind.Local).AddTicks(174),
                            Title = "Fantastic Steel Pants"
                        },
                        new
                        {
                            Id = 17,
                            Barcode = "3",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 824.229407654716m,
                            ReleaseDate = new DateTime(2026, 3, 17, 10, 30, 5, 151, DateTimeKind.Local).AddTicks(978),
                            Title = "Licensed Fresh Soap"
                        },
                        new
                        {
                            Id = 18,
                            Barcode = "7",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 212.783163749978m,
                            ReleaseDate = new DateTime(2026, 3, 14, 3, 14, 57, 263, DateTimeKind.Local).AddTicks(7772),
                            Title = "Refined Steel Soap"
                        },
                        new
                        {
                            Id = 19,
                            Barcode = "4",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 749.219822308617m,
                            ReleaseDate = new DateTime(2025, 10, 17, 5, 9, 40, 13, DateTimeKind.Local).AddTicks(586),
                            Title = "Generic Soft Keyboard"
                        },
                        new
                        {
                            Id = 20,
                            Barcode = "7",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 653.205129991847m,
                            ReleaseDate = new DateTime(2026, 8, 21, 17, 27, 51, 549, DateTimeKind.Local).AddTicks(1103),
                            Title = "Gorgeous Concrete Tuna"
                        },
                        new
                        {
                            Id = 21,
                            Barcode = "7",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 421.230083562075m,
                            ReleaseDate = new DateTime(2025, 9, 23, 19, 16, 47, 888, DateTimeKind.Local).AddTicks(2003),
                            Title = "Incredible Concrete Shoes"
                        },
                        new
                        {
                            Id = 22,
                            Barcode = "2",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 136.821059656246m,
                            ReleaseDate = new DateTime(2026, 2, 24, 18, 59, 38, 837, DateTimeKind.Local).AddTicks(1412),
                            Title = "Refined Rubber Pants"
                        },
                        new
                        {
                            Id = 23,
                            Barcode = "2",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 957.658069013459m,
                            ReleaseDate = new DateTime(2026, 9, 5, 6, 57, 25, 644, DateTimeKind.Local).AddTicks(6510),
                            Title = "Practical Plastic Hat"
                        },
                        new
                        {
                            Id = 24,
                            Barcode = "1",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 142.272277362771m,
                            ReleaseDate = new DateTime(2026, 7, 26, 3, 57, 43, 459, DateTimeKind.Local).AddTicks(65),
                            Title = "Handmade Soft Pizza"
                        },
                        new
                        {
                            Id = 25,
                            Barcode = "5",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 23.9252489027219m,
                            ReleaseDate = new DateTime(2026, 5, 16, 18, 0, 0, 165, DateTimeKind.Local).AddTicks(8944),
                            Title = "Practical Wooden Shoes"
                        },
                        new
                        {
                            Id = 26,
                            Barcode = "0",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 191.487272297259m,
                            ReleaseDate = new DateTime(2025, 11, 24, 19, 37, 14, 355, DateTimeKind.Local).AddTicks(7854),
                            Title = "Handcrafted Fresh Fish"
                        },
                        new
                        {
                            Id = 27,
                            Barcode = "1",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 561.967948376186m,
                            ReleaseDate = new DateTime(2026, 6, 7, 16, 9, 45, 757, DateTimeKind.Local).AddTicks(453),
                            Title = "Awesome Steel Computer"
                        },
                        new
                        {
                            Id = 28,
                            Barcode = "2",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 3.5221822948764m,
                            ReleaseDate = new DateTime(2025, 9, 29, 22, 19, 35, 420, DateTimeKind.Local).AddTicks(9341),
                            Title = "Fantastic Concrete Fish"
                        },
                        new
                        {
                            Id = 29,
                            Barcode = "9",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 904.469962442513m,
                            ReleaseDate = new DateTime(2025, 9, 15, 10, 1, 1, 251, DateTimeKind.Local).AddTicks(238),
                            Title = "Gorgeous Soft Cheese"
                        },
                        new
                        {
                            Id = 30,
                            Barcode = "1",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 746.896074790459m,
                            ReleaseDate = new DateTime(2025, 12, 13, 12, 29, 37, 660, DateTimeKind.Local).AddTicks(6084),
                            Title = "Ergonomic Rubber Chair"
                        },
                        new
                        {
                            Id = 31,
                            Barcode = "0",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 148.38073461474m,
                            ReleaseDate = new DateTime(2026, 4, 12, 11, 30, 6, 276, DateTimeKind.Local).AddTicks(463),
                            Title = "Sleek Wooden Chicken"
                        },
                        new
                        {
                            Id = 32,
                            Barcode = "9",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 417.814398632298m,
                            ReleaseDate = new DateTime(2025, 12, 15, 10, 42, 15, 666, DateTimeKind.Local).AddTicks(8398),
                            Title = "Unbranded Cotton Hat"
                        },
                        new
                        {
                            Id = 33,
                            Barcode = "6",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 852.765678265489m,
                            ReleaseDate = new DateTime(2026, 5, 20, 7, 50, 12, 27, DateTimeKind.Local).AddTicks(7270),
                            Title = "Incredible Plastic Bacon"
                        },
                        new
                        {
                            Id = 34,
                            Barcode = "5",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 804.236928754131m,
                            ReleaseDate = new DateTime(2025, 11, 17, 8, 8, 28, 207, DateTimeKind.Local).AddTicks(7879),
                            Title = "Gorgeous Rubber Shirt"
                        },
                        new
                        {
                            Id = 35,
                            Barcode = "4",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 26.2404758977892m,
                            ReleaseDate = new DateTime(2025, 11, 9, 10, 57, 23, 767, DateTimeKind.Local).AddTicks(8314),
                            Title = "Generic Concrete Chicken"
                        },
                        new
                        {
                            Id = 36,
                            Barcode = "7",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 725.144727047134m,
                            ReleaseDate = new DateTime(2026, 1, 27, 8, 5, 54, 605, DateTimeKind.Local).AddTicks(8599),
                            Title = "Incredible Soft Chair"
                        },
                        new
                        {
                            Id = 37,
                            Barcode = "3",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 803.266455316109m,
                            ReleaseDate = new DateTime(2026, 9, 9, 20, 9, 32, 23, DateTimeKind.Local).AddTicks(5884),
                            Title = "Generic Wooden Gloves"
                        },
                        new
                        {
                            Id = 38,
                            Barcode = "1",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 62.5145756315974m,
                            ReleaseDate = new DateTime(2025, 10, 27, 18, 12, 9, 384, DateTimeKind.Local).AddTicks(6259),
                            Title = "Licensed Frozen Bacon"
                        },
                        new
                        {
                            Id = 39,
                            Barcode = "4",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 237.21610888616m,
                            ReleaseDate = new DateTime(2025, 12, 3, 9, 17, 41, 336, DateTimeKind.Local).AddTicks(7108),
                            Title = "Awesome Steel Bike"
                        },
                        new
                        {
                            Id = 40,
                            Barcode = "5",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 423.906217697498m,
                            ReleaseDate = new DateTime(2025, 11, 25, 8, 31, 28, 904, DateTimeKind.Local).AddTicks(4004),
                            Title = "Licensed Cotton Chicken"
                        },
                        new
                        {
                            Id = 41,
                            Barcode = "6",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 348.033573048671m,
                            ReleaseDate = new DateTime(2026, 1, 12, 18, 59, 32, 481, DateTimeKind.Local).AddTicks(1180),
                            Title = "Licensed Soft Tuna"
                        },
                        new
                        {
                            Id = 42,
                            Barcode = "8",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 923.708887695199m,
                            ReleaseDate = new DateTime(2026, 4, 4, 17, 55, 38, 702, DateTimeKind.Local).AddTicks(7231),
                            Title = "Intelligent Steel Mouse"
                        },
                        new
                        {
                            Id = 43,
                            Barcode = "0",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 399.114577426163m,
                            ReleaseDate = new DateTime(2026, 5, 4, 7, 25, 42, 320, DateTimeKind.Local).AddTicks(9193),
                            Title = "Rustic Rubber Soap"
                        },
                        new
                        {
                            Id = 44,
                            Barcode = "6",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 567.6642325342m,
                            ReleaseDate = new DateTime(2025, 11, 23, 13, 39, 16, 81, DateTimeKind.Local).AddTicks(4466),
                            Title = "Generic Wooden Soap"
                        },
                        new
                        {
                            Id = 45,
                            Barcode = "6",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 177.533260105892m,
                            ReleaseDate = new DateTime(2025, 11, 22, 1, 22, 38, 291, DateTimeKind.Local).AddTicks(8751),
                            Title = "Small Metal Chair"
                        },
                        new
                        {
                            Id = 46,
                            Barcode = "2",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 811.113948725682m,
                            ReleaseDate = new DateTime(2025, 12, 20, 5, 5, 12, 982, DateTimeKind.Local).AddTicks(355),
                            Title = "Licensed Steel Pizza"
                        },
                        new
                        {
                            Id = 47,
                            Barcode = "2",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 695.593573097882m,
                            ReleaseDate = new DateTime(2026, 2, 28, 6, 43, 45, 188, DateTimeKind.Local).AddTicks(1591),
                            Title = "Incredible Plastic Mouse"
                        },
                        new
                        {
                            Id = 48,
                            Barcode = "6",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 647.554261952431m,
                            ReleaseDate = new DateTime(2025, 10, 24, 0, 57, 5, 115, DateTimeKind.Local).AddTicks(593),
                            Title = "Unbranded Frozen Shirt"
                        },
                        new
                        {
                            Id = 49,
                            Barcode = "5",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 434.967351342071m,
                            ReleaseDate = new DateTime(2025, 10, 28, 8, 15, 31, 429, DateTimeKind.Local).AddTicks(7249),
                            Title = "Generic Cotton Gloves"
                        },
                        new
                        {
                            Id = 50,
                            Barcode = "4",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 757.585922315058m,
                            ReleaseDate = new DateTime(2026, 6, 7, 7, 12, 45, 323, DateTimeKind.Local).AddTicks(8660),
                            Title = "Incredible Rubber Sausages"
                        },
                        new
                        {
                            Id = 51,
                            Barcode = "7",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 788.283209431583m,
                            ReleaseDate = new DateTime(2026, 8, 10, 10, 24, 50, 438, DateTimeKind.Local).AddTicks(759),
                            Title = "Intelligent Concrete Chips"
                        },
                        new
                        {
                            Id = 52,
                            Barcode = "5",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 450.797146271354m,
                            ReleaseDate = new DateTime(2026, 6, 25, 23, 39, 30, 511, DateTimeKind.Local).AddTicks(8940),
                            Title = "Tasty Soft Pants"
                        },
                        new
                        {
                            Id = 53,
                            Barcode = "9",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 470.599800235871m,
                            ReleaseDate = new DateTime(2025, 9, 25, 8, 22, 28, 732, DateTimeKind.Local).AddTicks(5049),
                            Title = "Unbranded Granite Sausages"
                        },
                        new
                        {
                            Id = 54,
                            Barcode = "7",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 434.606364188067m,
                            ReleaseDate = new DateTime(2026, 5, 21, 19, 39, 23, 265, DateTimeKind.Local).AddTicks(9671),
                            Title = "Unbranded Frozen Shoes"
                        },
                        new
                        {
                            Id = 55,
                            Barcode = "6",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 493.17411300129m,
                            ReleaseDate = new DateTime(2026, 3, 12, 3, 8, 32, 524, DateTimeKind.Local).AddTicks(6404),
                            Title = "Rustic Steel Ball"
                        },
                        new
                        {
                            Id = 56,
                            Barcode = "4",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 784.890900582024m,
                            ReleaseDate = new DateTime(2026, 4, 19, 3, 46, 32, 562, DateTimeKind.Local).AddTicks(3316),
                            Title = "Handmade Soft Salad"
                        },
                        new
                        {
                            Id = 57,
                            Barcode = "0",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 788.656938758985m,
                            ReleaseDate = new DateTime(2025, 12, 28, 4, 33, 30, 928, DateTimeKind.Local).AddTicks(6259),
                            Title = "Handcrafted Plastic Car"
                        },
                        new
                        {
                            Id = 58,
                            Barcode = "3",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 361.786875191511m,
                            ReleaseDate = new DateTime(2026, 7, 8, 8, 36, 14, 731, DateTimeKind.Local).AddTicks(6048),
                            Title = "Fantastic Cotton Shoes"
                        },
                        new
                        {
                            Id = 59,
                            Barcode = "5",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 998.108976057781m,
                            ReleaseDate = new DateTime(2026, 5, 5, 22, 41, 43, 447, DateTimeKind.Local).AddTicks(7495),
                            Title = "Practical Granite Car"
                        },
                        new
                        {
                            Id = 60,
                            Barcode = "0",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 971.996800778898m,
                            ReleaseDate = new DateTime(2026, 5, 24, 16, 50, 50, 661, DateTimeKind.Local).AddTicks(7971),
                            Title = "Unbranded Wooden Gloves"
                        },
                        new
                        {
                            Id = 61,
                            Barcode = "0",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 903.091018867721m,
                            ReleaseDate = new DateTime(2026, 6, 29, 19, 42, 18, 506, DateTimeKind.Local).AddTicks(1479),
                            Title = "Handcrafted Cotton Hat"
                        },
                        new
                        {
                            Id = 62,
                            Barcode = "7",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 638.596461951545m,
                            ReleaseDate = new DateTime(2026, 2, 24, 11, 15, 26, 793, DateTimeKind.Local).AddTicks(8071),
                            Title = "Refined Frozen Pizza"
                        },
                        new
                        {
                            Id = 63,
                            Barcode = "7",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 757.721955285278m,
                            ReleaseDate = new DateTime(2025, 9, 17, 11, 46, 31, 574, DateTimeKind.Local).AddTicks(2855),
                            Title = "Refined Concrete Towels"
                        },
                        new
                        {
                            Id = 64,
                            Barcode = "0",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 743.693539240255m,
                            ReleaseDate = new DateTime(2026, 1, 9, 9, 27, 34, 480, DateTimeKind.Local).AddTicks(7889),
                            Title = "Practical Frozen Bacon"
                        },
                        new
                        {
                            Id = 65,
                            Barcode = "3",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 643.732897129251m,
                            ReleaseDate = new DateTime(2025, 12, 23, 4, 40, 18, 325, DateTimeKind.Local).AddTicks(5955),
                            Title = "Generic Plastic Chair"
                        },
                        new
                        {
                            Id = 66,
                            Barcode = "8",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 421.864970457677m,
                            ReleaseDate = new DateTime(2026, 3, 23, 23, 49, 24, 524, DateTimeKind.Local).AddTicks(9921),
                            Title = "Handmade Steel Salad"
                        },
                        new
                        {
                            Id = 67,
                            Barcode = "6",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 166.650159618654m,
                            ReleaseDate = new DateTime(2025, 12, 29, 2, 22, 39, 794, DateTimeKind.Local).AddTicks(9826),
                            Title = "Tasty Wooden Ball"
                        },
                        new
                        {
                            Id = 68,
                            Barcode = "2",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 922.382416791461m,
                            ReleaseDate = new DateTime(2026, 3, 24, 18, 44, 53, 773, DateTimeKind.Local).AddTicks(4901),
                            Title = "Licensed Fresh Pizza"
                        },
                        new
                        {
                            Id = 69,
                            Barcode = "5",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 809.553099705164m,
                            ReleaseDate = new DateTime(2026, 3, 4, 11, 15, 40, 689, DateTimeKind.Local).AddTicks(9498),
                            Title = "Practical Rubber Shoes"
                        },
                        new
                        {
                            Id = 70,
                            Barcode = "7",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 655.430085775643m,
                            ReleaseDate = new DateTime(2026, 2, 5, 22, 50, 19, 656, DateTimeKind.Local).AddTicks(1805),
                            Title = "Generic Soft Fish"
                        },
                        new
                        {
                            Id = 71,
                            Barcode = "8",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 514.024618253123m,
                            ReleaseDate = new DateTime(2026, 7, 20, 8, 27, 17, 299, DateTimeKind.Local).AddTicks(9411),
                            Title = "Intelligent Frozen Car"
                        },
                        new
                        {
                            Id = 72,
                            Barcode = "0",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 962.847247140876m,
                            ReleaseDate = new DateTime(2025, 11, 19, 3, 36, 44, 351, DateTimeKind.Local).AddTicks(834),
                            Title = "Handmade Steel Mouse"
                        },
                        new
                        {
                            Id = 73,
                            Barcode = "7",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 342.365613256751m,
                            ReleaseDate = new DateTime(2026, 1, 25, 12, 31, 41, 424, DateTimeKind.Local).AddTicks(4823),
                            Title = "Practical Granite Ball"
                        },
                        new
                        {
                            Id = 74,
                            Barcode = "6",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 634.955703747904m,
                            ReleaseDate = new DateTime(2026, 9, 9, 9, 48, 10, 255, DateTimeKind.Local).AddTicks(2486),
                            Title = "Fantastic Concrete Towels"
                        },
                        new
                        {
                            Id = 75,
                            Barcode = "9",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 248.995546445248m,
                            ReleaseDate = new DateTime(2025, 12, 21, 19, 31, 9, 758, DateTimeKind.Local).AddTicks(9203),
                            Title = "Unbranded Soft Mouse"
                        },
                        new
                        {
                            Id = 76,
                            Barcode = "6",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 701.105381604333m,
                            ReleaseDate = new DateTime(2026, 2, 1, 4, 19, 9, 612, DateTimeKind.Local).AddTicks(1719),
                            Title = "Gorgeous Rubber Tuna"
                        },
                        new
                        {
                            Id = 77,
                            Barcode = "0",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 245.491691592844m,
                            ReleaseDate = new DateTime(2026, 9, 2, 13, 52, 18, 488, DateTimeKind.Local).AddTicks(3891),
                            Title = "Practical Cotton Keyboard"
                        },
                        new
                        {
                            Id = 78,
                            Barcode = "2",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 478.180023406716m,
                            ReleaseDate = new DateTime(2025, 11, 22, 21, 56, 40, 376, DateTimeKind.Local).AddTicks(3621),
                            Title = "Fantastic Frozen Salad"
                        },
                        new
                        {
                            Id = 79,
                            Barcode = "2",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 730.923636926302m,
                            ReleaseDate = new DateTime(2025, 12, 21, 19, 40, 26, 999, DateTimeKind.Local).AddTicks(5333),
                            Title = "Awesome Rubber Hat"
                        },
                        new
                        {
                            Id = 80,
                            Barcode = "0",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 380.033881022611m,
                            ReleaseDate = new DateTime(2026, 1, 7, 22, 36, 6, 575, DateTimeKind.Local).AddTicks(5066),
                            Title = "Handmade Plastic Cheese"
                        },
                        new
                        {
                            Id = 81,
                            Barcode = "9",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 321.162595319637m,
                            ReleaseDate = new DateTime(2026, 7, 25, 13, 39, 29, 676, DateTimeKind.Local).AddTicks(7886),
                            Title = "Sleek Frozen Table"
                        },
                        new
                        {
                            Id = 82,
                            Barcode = "4",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 288.791837182265m,
                            ReleaseDate = new DateTime(2025, 11, 16, 2, 37, 9, 243, DateTimeKind.Local).AddTicks(2444),
                            Title = "Small Cotton Chips"
                        },
                        new
                        {
                            Id = 83,
                            Barcode = "0",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 664.62972283998m,
                            ReleaseDate = new DateTime(2026, 9, 5, 17, 24, 38, 255, DateTimeKind.Local).AddTicks(3611),
                            Title = "Gorgeous Cotton Mouse"
                        },
                        new
                        {
                            Id = 84,
                            Barcode = "3",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 852.271434428762m,
                            ReleaseDate = new DateTime(2025, 10, 8, 18, 56, 11, 629, DateTimeKind.Local).AddTicks(6953),
                            Title = "Handcrafted Granite Mouse"
                        },
                        new
                        {
                            Id = 85,
                            Barcode = "5",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 78.5820450538686m,
                            ReleaseDate = new DateTime(2025, 11, 12, 20, 43, 48, 306, DateTimeKind.Local).AddTicks(8123),
                            Title = "Tasty Fresh Chair"
                        },
                        new
                        {
                            Id = 86,
                            Barcode = "6",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 902.329506187853m,
                            ReleaseDate = new DateTime(2025, 11, 13, 22, 0, 39, 340, DateTimeKind.Local).AddTicks(6699),
                            Title = "Generic Rubber Gloves"
                        },
                        new
                        {
                            Id = 87,
                            Barcode = "5",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 467.696303133711m,
                            ReleaseDate = new DateTime(2026, 6, 19, 19, 52, 56, 65, DateTimeKind.Local).AddTicks(7614),
                            Title = "Tasty Fresh Car"
                        },
                        new
                        {
                            Id = 88,
                            Barcode = "8",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 621.782007443617m,
                            ReleaseDate = new DateTime(2026, 6, 22, 15, 20, 42, 884, DateTimeKind.Local).AddTicks(9478),
                            Title = "Generic Wooden Hat"
                        },
                        new
                        {
                            Id = 89,
                            Barcode = "2",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 671.673668492899m,
                            ReleaseDate = new DateTime(2025, 12, 18, 15, 22, 24, 174, DateTimeKind.Local).AddTicks(5659),
                            Title = "Licensed Concrete Towels"
                        },
                        new
                        {
                            Id = 90,
                            Barcode = "9",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 266.666077669554m,
                            ReleaseDate = new DateTime(2026, 6, 2, 12, 51, 35, 709, DateTimeKind.Local).AddTicks(5839),
                            Title = "Incredible Wooden Mouse"
                        },
                        new
                        {
                            Id = 91,
                            Barcode = "9",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 479.420829466274m,
                            ReleaseDate = new DateTime(2026, 3, 24, 13, 37, 7, 311, DateTimeKind.Local).AddTicks(5572),
                            Title = "Handcrafted Granite Chicken"
                        },
                        new
                        {
                            Id = 92,
                            Barcode = "5",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 396.853495480424m,
                            ReleaseDate = new DateTime(2026, 7, 2, 0, 13, 20, 857, DateTimeKind.Local).AddTicks(9747),
                            Title = "Small Concrete Hat"
                        },
                        new
                        {
                            Id = 93,
                            Barcode = "3",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 428.859090867852m,
                            ReleaseDate = new DateTime(2026, 8, 31, 23, 7, 12, 676, DateTimeKind.Local).AddTicks(6444),
                            Title = "Small Soft Soap"
                        },
                        new
                        {
                            Id = 94,
                            Barcode = "2",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 227.56040147299m,
                            ReleaseDate = new DateTime(2025, 12, 31, 14, 40, 57, 695, DateTimeKind.Local).AddTicks(3835),
                            Title = "Licensed Plastic Fish"
                        },
                        new
                        {
                            Id = 95,
                            Barcode = "7",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 844.347017200825m,
                            ReleaseDate = new DateTime(2026, 7, 31, 1, 8, 37, 598, DateTimeKind.Local).AddTicks(2777),
                            Title = "Refined Steel Keyboard"
                        },
                        new
                        {
                            Id = 96,
                            Barcode = "2",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 771.981288391622m,
                            ReleaseDate = new DateTime(2026, 5, 8, 20, 19, 25, 541, DateTimeKind.Local).AddTicks(1555),
                            Title = "Sleek Metal Gloves"
                        },
                        new
                        {
                            Id = 97,
                            Barcode = "6",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 322.036397850158m,
                            ReleaseDate = new DateTime(2026, 3, 10, 23, 1, 43, 867, DateTimeKind.Local).AddTicks(8648),
                            Title = "Unbranded Steel Ball"
                        },
                        new
                        {
                            Id = 98,
                            Barcode = "6",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 74.260098103555m,
                            ReleaseDate = new DateTime(2025, 12, 2, 5, 54, 7, 785, DateTimeKind.Local).AddTicks(9001),
                            Title = "Fantastic Cotton Chicken"
                        },
                        new
                        {
                            Id = 99,
                            Barcode = "5",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 427.946504512777m,
                            ReleaseDate = new DateTime(2026, 5, 18, 6, 27, 43, 278, DateTimeKind.Local).AddTicks(9367),
                            Title = "Refined Metal Chicken"
                        },
                        new
                        {
                            Id = 100,
                            Barcode = "9",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 590.502272143263m,
                            ReleaseDate = new DateTime(2026, 1, 14, 5, 38, 28, 583, DateTimeKind.Local).AddTicks(5603),
                            Title = "Handcrafted Plastic Car"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
